# Generated by Django 3.2.9 on 2021-11-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messaging',
            name='result',
        ),
        migrations.AddField(
            model_name='messaging',
            name='content',
            field=models.TextField(default='Hi there!', max_length=200),
        ),
    ]
