# Generated by Django 3.2.9 on 2021-11-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0003_auto_20211115_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='otp',
            new_name='unique',
        ),
    ]
