# Generated by Django 3.2.9 on 2021-11-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0004_rename_otp_person_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='passwrod1',
            field=models.TextField(default='QWERTY12345!@@!', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='passwrod2',
            field=models.TextField(default='QWERTY12345!@@!', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='unique',
            field=models.TextField(help_text='Unique ID for this person', primary_key=True, serialize=False),
        ),
    ]
