# Generated by Django 3.2.9 on 2021-11-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0005_auto_20211116_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='passwrod1',
        ),
        migrations.RemoveField(
            model_name='person',
            name='passwrod2',
        ),
        migrations.AlterField(
            model_name='person',
            name='unique',
            field=models.UUIDField(help_text='Unique ID for this person', primary_key=True, serialize=False),
        ),
    ]
