# Generated by Django 3.2.9 on 2021-11-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0006_auto_20211116_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='unique',
            field=models.TextField(help_text='Unique ID for this person', primary_key=True, serialize=False),
        ),
    ]
