# Generated by Django 3.2.9 on 2021-11-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0008_auto_20211116_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='emailid',
            field=models.CharField(default='Emailid@server.com', max_length=80),
        ),
        migrations.AlterField(
            model_name='person',
            name='qwertypass',
            field=models.CharField(default='Passwrod12345!@', max_length=20),
        ),
    ]
