# Generated by Django 3.2.9 on 2021-11-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0009_auto_20211116_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='emailid',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='person',
            name='qwertypass',
            field=models.CharField(max_length=20),
        ),
    ]
