# Generated by Django 3.2.9 on 2021-11-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0010_auto_20211116_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='emailid',
            field=models.EmailField(max_length=80),
        ),
    ]
